# Generated by Django 4.2.3 on 2024-07-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resident", "0002_visitor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resident",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("DL", "Daily Pass"),
                    ("ML", "Monthly Pass"),
                    ("WL", "Weekly Pass"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("DL", "Daily Pass"),
                    ("ML", "Monthly Pass"),
                    ("WL", "Weekly Pass"),
                ],
                max_length=10,
            ),
        ),
    ]
