# Generated by Django 4.2.3 on 2024-07-02 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0001_initial"),
        ("vehicle", "0003_remove_vehicle_code_remove_vehicle_owner_contact_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="owner",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_person",
                to="person.person",
            ),
        ),
    ]
