# Generated by Django 4.2.3 on 2024-07-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="doc_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DL", "Daily Pass"),
                    ("ML", "Monthly Pass"),
                    ("WL", "Weekly Pass"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
