# Generated by Django 4.2.3 on 2024-06-14 15:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("cctv", "0002_camera_is_gate_lpr"),
    ]

    operations = [
        migrations.AddField(
            model_name="lpr",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
