# Generated by Django 4.2.3 on 2024-06-14 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cctv", "0003_lpr_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="lpr",
            name="camera",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cctv.camera",
            ),
        ),
        migrations.AddField(
            model_name="lpr",
            name="channel_id",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
