# Generated by Django 4.2.3 on 2024-07-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cctv", "0006_commandcenter"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LPR",
        ),
    ]
