# Generated by Django 4.2.3 on 2024-08-28 05:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cctv", "0007_delete_lpr"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="coordinate",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, help_text="field untuk koordinat", null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="camera",
            name="icon_rotation",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Field untuk rotasi ikon, range 0.00 - 359.99",
                max_digits=5,
                null=True,
            ),
        ),
    ]
