# Generated by Django 4.2.3 on 2024-07-02 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cctv", "0006_commandcenter"),
        ("vehicle", "0003_remove_vehicle_code_remove_vehicle_owner_contact_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LPR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("channel_id", models.CharField(max_length=100)),
                ("number_plate", models.CharField(max_length=100)),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "IN"), ("out", "OUT"), ("unknown", "UNKNOWN")],
                        max_length=20,
                    ),
                ),
                ("time_utc_timestamp", models.BigIntegerField()),
                (
                    "camera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_camera",
                        to="cctv.camera",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_vehicle",
                        to="vehicle.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "LPR",
                "verbose_name_plural": "LPRs",
            },
        ),
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nonce", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "id32",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True)),
                ("created_at_timestamp", models.PositiveIntegerField(db_index=True)),
                (
                    "owned_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "owned_at_timestamp",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "updated_at_timestamp",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "published_at_timestamp",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("unpublished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "unpublished_at_timestamp",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_at_timestamp",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("unapproved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "unapproved_at_timestamp",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_at_timestamp",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("check_in_timestamp", models.BigIntegerField()),
                ("check_out_timestamp", models.BigIntegerField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_approved_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CheckIn",
                "verbose_name_plural": "CheckIns",
            },
        ),
    ]
