# Generated by Django 4.2.3 on 2024-07-26 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("activity", "0003_alter_checkin_options_alter_lpr_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lpr",
            name="snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_snapshot",
                to="common.file",
            ),
        ),
    ]
