# Generated by Django 4.2.3 on 2024-09-18 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0005_checkin_visitor_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="camera_photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_camera_photo",
                to="common.file",
            ),
        ),
    ]
